### ISSUE TITLE
Default CFDP config paths point to invalid directory structure

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-DSN#21]
The default CFDP config paths evaluate to paths that don't exist in the repo on a clean checkout. We should update the handling of this so that we emit a warning when a path doesn't exist and automatically create it as needed or we should fail loudly and early. Any config that should be kept and versioned (probably the MIB?) should end up in the `config/` directory somewhere as well.

```
            mib:
                path: ../tmp/mib
            outgoing:
                path: ../tmp/outgoing
            incoming:
                path: ../tmp/incoming
            temp:
                path: ../tmp/temp
            pdu:
                path: ../tmp/pdu
            test:
                path: ../tmp/test
```
