### ISSUE TITLE
Default SLE config parameters should be functional / provide sane defaults

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-DSN#77]
The current SLE config parameters don't provide sane defaults where options exist.

```
sle:
            initiator_id: uname
            password: pw
            responder_id: uname
            peer_password: pw
            version: 5
            downlink_frame_type: TMTransFrame
            heartbeat: heartbeat
            deadfactor: deadfactor
            buffer_size: buffer_size
            responder_port: responder_port
            auth_level: auth_level
```

These have defaults in `common.py` if they're not present in `config.yaml` but preference is given to config values. All of these need updated to mirror the default if they're going to be included or they need removed. I'm +1 to including them as an FYI for what can be adjusted.

```
sle:
            initiator_id: LSE
            # password only matters if we're doing auth and can stay as 'pw'
            password: pw
            responder_id: SSE
            # peer password only matters if we're doing auth and can stay as 'pw'
            peer_password: pw
            version: 5
            downlink_frame_type: TMTransFrame
            heartbeat: 25
            deadfactor: 5
            buffer_size: 256000
            responder_port: 'default'
            auth_level: 'none'
```
